/*
* ShieldingPage constants
*/

export const CHANGE_SELECTED_TOKEN = 'pstuff/ShieldingPage/CHANGE_SELECTED_TOKEN';
export const CHANGE_AMOUNT = 'pstuff/ShieldingPage/CHANGE_AMOUNT';

export const GET_LATEST_UNSUCCESSFUL_SHIELDING = 'pstuff/ShieldingPage/GET_LATEST_UNSUCCESSFUL_SHIELDING';
export const GET_LATEST_UNSUCCESSFUL_SHIELDING_SUCCESS = 'pstuff/ShieldingPage/GET_LATEST_UNSUCCESSFUL_SHIELDING_SUCCESS';
export const GET_LATEST_UNSUCCESSFUL_SHIELDING_FAILURE = 'pstuff/ShieldingPage/GET_LATEST_UNSUCCESSFUL_SHIELDING_FAILURE';

export const REFRESH_SHIELDING_PROOF_STEP = 'pstuff/ShieldingPage/REFRESH_SHIELDING_PROOF_STEP';
export const REFRESH_SHIELDING_PROOF_STEP_SUCCESS = 'pstuff/ShieldingPage/REFRESH_SHIELDING_PROOF_STEP_SUCCESS';
export const REFRESH_SHIELDING_PROOF_STEP_FAILURE = 'pstuff/ShieldingPage/REFRESH_SHIELDING_PROOF_STEP_FAILURE';

export const UPDATE_SHIELDING = 'pstuff/ShieldingPage/UPDATE_SHIELDING';
export const UPDATE_SHIELDING_SUCCESS = 'pstuff/ShieldingPage/UPDATE_SHIELDING_SUCCESS';
export const UPDATE_SHIELDING_FAILURE = 'pstuff/ShieldingPage/UPDATE_SHIELDING_FAILURE';

export const INSUFFICIENT_BALANCES = 'pstuff/ShieldingPage/INSUFFICIENT_BALANCES';
export const SKIP_FORM = 'pstuff/ShieldingPage/SKIP_FORM';
export const TESTNET_SHIELD_LOCAL_STORAGE = 'pstuff/ShieldingPage/TESTNET_SHIELD_LOCAL_STORAGE';
export const MAINNET_SHIELD_LOCAL_STORAGE = 'pstuff/ShieldingPage/MAINNET_SHIELD_LOCAL_STORAGE';
export const TOOL_TIP_HANDLER = 'pstuff/ShieldingPage/TOOL_TIP_HANDLER';