/*
* UndeployPage constants
*/

export const CHANGE_SELECTED_TOKEN = 'pstuff/UndeployPage/CHANGE_SELECTED_TOKEN';
export const CHANGE_AMOUNT = 'pstuff/UndeployPage/CHANGE_AMOUNT';

export const GET_LATEST_UNSUCCESSFUL_UNDEPLOY_SUCCESS = 'pstuff/UndeploygPage/GET_LATEST_UNSUCCESSFUL_UNDEPLOY_SUCCESS';
export const GET_LATEST_UNSUCCESSFUL_UNDEPLOY_FAILURE = 'pstuff/UndeploygPage/GET_LATEST_UNSUCCESSFUL_UNDEPLOY_FAILURE';

export const REFRESH_UNDEPLOY_PROOF_STEP_SUCCESS = 'pstuff/UndeploygPage/REFRESH_UNDEPLOY_PROOF_STEP_SUCCESS';
export const REFRESH_UNDEPLOY_PROOF_STEP_FAILURE = 'pstuff/UndeploygPage/REFRESH_UNDEPLOY_PROOF_STEP_FAILURE';

export const UPDATE_UNDEPLOY_SUCCESS = 'pstuff/UndeploygPage/UPDATE_UNDEPLOY_SUCCESS';
export const UPDATE_UNDEPLOY_FAILURE = 'pstuff/UndeploygPage/UPDATE_UNDEPLOY_FAILURE';

export const INSUFFICIENT_BALANCES = 'pstuff/UndeployPage/INSUFFICIENT_BALANCES';

export const SKIP_FORM = 'pstuff/UndeployPage/SKIP_FORM';
export const TESTNET_UNDEPLOY_LOCAL_STORAGE = 'pstuff/UndeployPage/TESTNET_SHIELD_LOCAL_STORAGE';
export const MAINNET_UNDEPLOY_LOCAL_STORAGE = 'pstuff/UndeployPage/MAINNET_SHIELD_LOCAL_STORAGE';
export const TOOL_TIP_HANDLER = 'pstuff/UndeployPage/TOOL_TIP_HANDLER';
export const UPDATE_VALIDATE_INPUT = 'pstuff/UndeployPage/UPDATE_VALIDATE_INPUT';