/*
* UndeployPage constants
*/

export const CHANGE_SELECTED_TOKEN = 'pstuff/UndeployPage/CHANGE_SELECTED_TOKEN';
export const CHANGE_AMOUNT = 'pstuff/UndeployPage/CHANGE_AMOUNT';

export const GET_LATEST_UNSUCCESSFUL_UNDEPLOY_SUCCESS = 'pstuff/UndeploygPage/GET_LATEST_UNSUCCESSFUL_UNDEPLOY_SUCCESS';
export const GET_LATEST_UNSUCCESSFUL_UNDEPLOY_FAILURE = 'pstuff/UndeploygPage/GET_LATEST_UNSUCCESSFUL_UNDEPLOY_FAILURE';

export const REFRESH_UNDEPLOY_PROOF_STEP_SUCCESS = 'pstuff/UndeploygPage/REFRESH_UNDEPLOY_PROOF_STEP_SUCCESS';
export const REFRESH_UNDEPLOY_PROOF_STEP_FAILURE = 'pstuff/UndeploygPage/REFRESH_UNDEPLOY_PROOF_STEP_FAILURE';

export const UPDATE_UNDEPLOY_SUCCESS = 'pstuff/UndeploygPage/UPDATE_UNDEPLOY_SUCCESS';
export const UPDATE_UNDEPLOY_FAILURE = 'pstuff/UndeploygPage/UPDATE_UNDEPLOY_FAILURE';

export const INSUFFICIENT_BALANCES = 'pstuff/UndeployPage/INSUFFICIENT_BALANCES';